export const blogCards = [
  {
    id: "0",
    imgSrc: "/images/blog/grid1.svg",
    imgAlt: "Grid 1",
    title: "Mai Profile News Letter 2024",
    passageMain: "Over the past few months we have been hard at work adding new features to mai profile.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    passage1: "Mai Profile has introduced several new tools and functionalities designed to enhance user experience.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus." ,
    passage2: "These updates include a new user interface, advanced analytics, and more customization options.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    author: {
      name: "Anna Philip",
      designation: "Senior Writer",
      imageUrl: "/images/blog/anna.jpeg",
    },
    publishedDate: "New York,16th June 2023",
    readTime: "5 min read",
    lastUpdatedDate: "16th June 2024",
    happenedDate: "15th June 2023",
  },
  {
    id: "1",
    imgSrc: "/images/blog/grid2.svg",
    imgAlt: "Grid 2",
    title: "What is the correct approach to Business Networking?",
    passageMain: "Over the past few months we have been hard at work adding new features to mai profile.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    passage1: "Mai Profile has introduced several new tools and functionalities designed to enhance user experience.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus." ,
    passage2: "These updates include a new user interface, advanced analytics, and more customization options.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    author: {
      name: "John Doe",
      designation: "Networking Expert",
      imageUrl: "/images/blog/john.jpeg",
    },
    publishedDate: "New York,16th June 2023",
    readTime: "7 min read",
    lastUpdatedDate: "16th June 2024",
    newsPlace: "London",
    happenedDate: "11th May 2023",
  },
  {
    slug: "How-to-Create-a-Virtual-Background",
    id: "2",
    imgSrc: "/images/blog/grid3.svg",
    imgAlt: "Grid 3",
    title: "How to Create a Virtual Background",
    passageMain: "Over the past few months we have been hard at work adding new features to mai profile.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    passage1: "Mai Profile has introduced several new tools and functionalities designed to enhance user experience.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus." ,
    passage2: "These updates include a new user interface, advanced analytics, and more customization options.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    author: {
      name: "Emily Smith",
      designation: "Tech Writer",
      imageUrl: "/images/blog/emily.jpeg",
    },
    publishedDate: "New York,16th June 2023",
    readTime: "6 min read",
    lastUpdatedDate: "16th June 2024",
    newsPlace: "San Francisco",
    happenedDate: "9th April 2023",
  },
  {
    imgSrc: "/Images/blog/grid4.svg",
    id: "3",
    imgAlt: "Grid 4",
    title: "Want to meet people faster Use this QR code Generator and Reader",
    passageMain: "Over the past few months we have been hard at work adding new features to mai profile.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    passage1: "Mai Profile has introduced several new tools and functionalities designed to enhance user experience.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus." ,
    passage2: "These updates include a new user interface, advanced analytics, and more customization options.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    author: {
      name: "Michael Johnson",
      designation: "Digital Marketer",
      imageUrl: "/images/blog/michael.avif",
    },
    publishedDate: "New York,16th June 2023",
    readTime: "8 min read",
    lastUpdatedDate: "16th June 2024",
    newsPlace: "Berlin",
    happenedDate: "7th March 2023",
  },
  {

    id: "4",
    imgSrc: "/images/blog/grid5.svg",
    imgAlt: "Grid 5",
    title: "How To Use a Virtual Background With Skype",
    passageMain: "Over the past few months we have been hard at work adding new features to mai profile.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    passage1: "Mai Profile has introduced several new tools and functionalities designed to enhance user experience.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus." ,
    passage2: "These updates include a new user interface, advanced analytics, and more customization options.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Velit qui architecto dicta at aliquid rem perferendis necessitatibus accusamus cum beatae minima, natus, soluta dolore id reprehenderit. Numquam, natus ullam! Aliquam doloribus amet delectus deleniti quos quaerat vero culpa possimus! Cupiditate neque doloribus sit ut totam illo quod asperiores modi minus.",
    titleWidth: "w-[300px]",
    author: {
      name: "Sarah Lee",
      designation: "Software Engineer",
      imageUrl: "/images/blog/sarah.jpeg",
    },
    publishedDate: "New York,16th June 2023",
    readTime: "4 min read",
    lastUpdatedDate: "16th June 2024",
    newsPlace: "Tokyo",
    happenedDate: "31st January 2023",
  },
];

