//mappapble constant data can be used here (static data)
import f1 from '../public/Images/features/Icon1.svg'
import f2 from '../public/Images/features/Icon2.svg'
import f3 from '../public/Images/features/Icon3.svg'

export const featuresHome=[
 {
    id:1,
    image:f1,
    title:"Online Profile Portfolio Creation",
    desc:"Craft professional online portfolios effortlessly to stand out in your field."
 },
 {
    id:2,
    image:f2,
    title:"NFC Digital Visiting Cards",
    desc:"Share contact info and portfolios with a tap using interactive NFC cards."
 },
 {
    id:3,
    image:f3,
    title:"Cost effective Digital Identity-Solutions",
    desc:"Affordable solutions tailored for individuals and businesses to enhance their online presence."
 },
]

export const ourValues=[
   {
      id:1,
      title:"Innovation",
      desc:" We are committed to continuously innovating and staying at the forefront of technology to provide our customers with the most advanced NFC digital business card solutions."
   },
   {
      id:2,
      title:"Simplicity",
      desc:"We believe in simplicity and ease of use. Our NFC digital business cards are designed to streamline networking processes, making it effortless for users to exchange information and connect with others."
   },
   {
      id:3,
      title:"Quality",
      desc:" We prioritize quality in every aspect of our products and services. From the materials used to craft our NFC digital business cards to the functionality and reliability of our technology, we uphold the highest standards to ensure customer satisfaction."
   },
   {
      id:4,
      title:"Connection",
      desc:"At the heart of our values lies the belief in the power of connection. We strive to facilitate meaningful connections between individuals by providing tools that enable seamless networking experiences with our  cards."
   },
  ]
  export const howItWork = [
   {
     desc: "Creating an account is your gateway to unlocking a world of professional networking possibilities.",
     title: "Create your account & start your work",
     smallImg: "Images/howitwork/1.svg",
     imgSrc: "Images/howitwork/3.svg",
     rating: 4,
   },
   {
     desc: "Provide essential information like your name, job title, and contact details.",
     title: "Add your Detailed professional background",
     smallImg: "Images/howitwork/2.svg",
     imgSrc: "Images/howitwork/5.svg",
     rating: 3,
   },
   {
     desc: "Simply copy and paste the unique link generated by our platform into emails, social media bios, or messaging apps.",
     title: "Share your digital profile or NFC-card link effortlessly",
     smallImg: "Images/howitwork/4.svg",
     imgSrc: "Images/howitwork/6.svg",
     rating: 5,
   },
 ];
 export const templatedata = [
   {
     img:"/Images/templates/dp1.svg",
     name: "Arun C",
     designation: "UI/UX Designer",
     about: "Developing intuitive and engaging user interfaces for digital purposes.",
     email: "arunc12@gmail.com",
     mobile: "+91 7994185674",
     website: "www.arunc.com",
     linkedin: "Arun C",
     aboutme: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design.",
     servicesOffered: ["Web Design", "Mobile App Design", "Brand Identity"],
     education: ["SSLC", "Plus Two In Computer Science", "Diploma In DPSE", "Diploma in UiUx Design"],
     certifications: [
       { year: "2020", institute: "Design Institute", certification: "Certified UX Designer" },
       { year: "2018", institute: "Tech University", certification: "Certified Web Developer" },
     ],
     achievements: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design.",
     languages: ["Hindi", "English", "Malayalam", "Tamil"],
     hobbies: ["Gaming", "Swimming", "Reading", "Dancing"],
     recentWorks: [
       {
         image: "/Images/templates/unsplash.svg",
         projectName: "Project Name",
         details: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design",
       },
       {
         image: "/Images/templates/unsplash.svg",
         projectName: "Project Name",
         details: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design",
       },
       {
         image: "/Images/templates/unsplash.svg",
         projectName: "Project Name",
         details: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design",
       },
     
     ],
   },
 ];

 export const templatedata2 = [
   {
     img:"/Images/templates/dp1.svg",
     name: "Jennifer John",
     designation: "UI/UX Designer",
     about: "Developing intuitive and engaging user interfaces for digital purposes.",
     email: "jenniferjohn12@gmail.com",
     mobile: "+91 8489898398",
     website: "www.jennifer.com",
     linkedin: "Jennifer John",
     aboutme: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design.",
     servicesOffered: ["Web Design", "Mobile App Design", "Brand Identity"],
     education: ["SSLC", "Plus Two In Computer Science", "Diploma In DPSE", "Diploma in UiUx Design"],
     certifications: [
       { year: "2020", institute: "Design Institute", certification: "Certified UX Designer" },
       { year: "2018", institute: "Tech University", certification: "Certified Web Developer" },
     ],
     achievements: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design.",
     languages: ["Hindi", "English", "Malayalam", "Tamil"],
     hobbies: ["Gaming", "Swimming", "Reading", "Dancing"],
     recentWorks: [
       {
         image: "/Images/templates/proj2.svg",
         projectName: "Project Name",
         details: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design",
       },
       {
         image: "/Images/templates/proj1.svg",
         projectName: "Project Name",
         details: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design",
       },
       {
         image: "/Images/templates/proj3.svg",
         projectName: "Project Name",
         details: "I'm a UX/UI Designer with a background in Psychology, which gives me a unique edge in empathizing with users and improving their experience through design",
       },
     
     ],
   },
 ];