"use client";

import React, { useState, useEffect, useCallback } from "react";
import useEmblaCarousel from "embla-carousel-react";
import Autoplay from "embla-carousel-autoplay";
import { CircleUserRound } from "lucide-react";
import Image from "next/image";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";

const HowItWorkSlider = () => {
  const [emblaRef, embla] = useEmblaCarousel({ loop: true }, [
    Autoplay({ delay: 4000 }),
  ]);
  const [activeIndex, setActiveIndex] = useState(0);

  const onSelect = useCallback(() => {
    if (!embla) return;
    setActiveIndex(embla.selectedScrollSnap());
  }, [embla]);

  useEffect(() => {
    if (!embla) return;
    embla.on("select", onSelect);
    onSelect();
  }, [embla, onSelect]);

  const scrollTo = (index: any) => {
    if (embla) embla.scrollTo(index);
  };

  const howItWork = [
    {
      desc: "Creating an account is your gateway to unlocking a world of professional networking possibilities.",
      title: "Create your account & start your work",
      smallImg: "Images/howitwork/1.svg",
      imgSrc: "Images/howitwork/3.svg",
      rating: 4,
    },
    {
      desc: "Provide essential information like your name, job title, and contact details.",
      title: "Add your Detailed professional background",
      smallImg: "Images/howitwork/2.svg",
      imgSrc: "Images/howitwork/5.svg",
      rating: 3,
    },
    {
      desc: "Simply copy and paste the unique link generated by our platform into emails, social media bios, or messaging apps.",
      title: "Share your digital profile or NFC-card link effortlessly",
      smallImg: "Images/howitwork/4.svg",
      imgSrc: "Images/howitwork/6.svg",
      rating: 5,
    },
  ];

  return (
    <div className="px-2 max-w-[1400px] overflow-hidden mx-auto lg:pt-12 lg:px-[10vw] md:px-[5vw] pt-3 font-concord font-normal pb-16">
      <span className="bg-primary-blue lg:rounded-full lg:p-4 lg:w-32 lg:text-sm text-white p-2 mx-auto rounded-md justify-center flex w-24 text-xs">
        How It Work{" "}
      </span>
      <p className="text-[20px] font-medium text-primary-blue px-4 tracking-wide lg:pt-6 lg:pb-1 md:text-2xl lg:text-4xl md:leading-6 text-center md:mb-5 leading-5 pt-2">
        Work smarter <br />
        with easy access for user..{" "}
      </p>

      <div className="flex text-[10px] md:text-base xl:text-[22px] lg:text-xl justify-around gap-2 pt-4">
        <span
          className={`${activeIndex === 0 ? "bg-primary-blue text-white" : "bg-[#F9F9F9]"} z-40 xl:p-7 xl:rounded-2xl cursor-pointer xl:px-20 p-2 md:p-4 md:px-8 lg:p-6 lg:px-14 whitespace-nowrap rounded-md`}
          onClick={() => scrollTo(0)}
        >
          01. Create account
        </span>
        <span
          className={`${activeIndex === 1 ? "bg-primary-blue text-white" : "bg-[#F9F9F9]"} z-40 xl:p-7 xl:rounded-2xl cursor-pointer xl:px-20 p-2 md:p-4 md:px-8 lg:p-6 lg:px-14 whitespace-nowrap rounded-md`}
          onClick={() => scrollTo(1)}
        >
          02. Enter your details
        </span>
        <span
          className={`${activeIndex === 2 ? "bg-primary-blue text-white" : "bg-[#F9F9F9]"} z-40 xl:p-7 xl:rounded-2xl cursor-pointer xl:px-20 p-2 md:p-4 md:px-8 lg:p-6 lg:px-14 whitespace-nowrap rounded-md`}
          onClick={() => scrollTo(2)}
        >
          03. Share the Link
        </span>
      </div>

      <div className="embla relative z-40" ref={emblaRef}>
        <div className="embla__container">
          {howItWork.map((testimonial, index) => (
            <div className="embla__slide" key={index}>
              <div className="relative z-10 bg-white">
                <div className="pt-10 lg:pt-16 h-full">
                  <div className="flex justify-center md:justify-between items-stretch h-full md:px-4 lg:px-14">
                    <div className="relative z-10 flex flex-col justify-between">
                      <div className="flex gap-2 md:gap-4 lg:gap-6 items-center">
                      <Image
                        src={testimonial.smallImg}
                        width={10}
                        height={10}
                        alt="hero"
                        className=" xl:w-20 xl:h-20 w-8 lg:w-14 md:mt-0 md:mb-3 lg:mb-0  mt-6 mb-10"
                      />                   <span className="text-lg z-40 bg-white lg:max-w-[350px] md:max-w-[200px]  leading-5 md:text-xl lg:text-3xl lg:leading-8 md:leading-5">
                          {testimonial.title}
                        </span>
                      </div>
                      <p className="text-[10px] z-40 bg-white text-[#797979] lg:text-base lg:w-[380px] xl:w-[430px] md:w-[300px] md:text-[12px]">
                        {testimonial.desc}
                      </p>
                      <span className="bg-primary-blue z-50 text-white p-2 md:text-sm lg:p-4 lg:px-9 mb-0 rounded-lg lg:rounded-full text-[10px] lg:max-w-[150px] md:max-w-[100px]   max-w-[70px]">
                        Get started
                      </span>
                    </div>

                    <div className="lg:flex lg:justify-end   relative z-10">
                      <Image
                        src={testimonial.imgSrc}
                        width={284}
                        height={190}
                        alt="hero"
                        className="xl:w-3/4 lg:w-full md:mt-0 md:mb-3 lg:mb-0  mt-6 mb-10"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default HowItWorkSlider;
